# General settings
lidar_frequency: 10

#distance threshold
threshold: 10 

#Countdown before deleting a tracker
countdown: 1

#Velocity
ignore_velocity: False
velocity_threshold: 50

#Tracking box colors
box_colors: [
    [0.4, 0.1, 0.9],
    [0.9, 0.2, 0.5],
    [0.1, 0.8, 0.4],
    [0.9, 0.7, 0.2],
    [0.6, 0.3, 0.1],
    [0.2, 0.5, 0.7],
    [0.7, 0.6, 0.3],
    [0.1, 0.9, 0.6],
    [0.5, 0.4, 0.8],
    [0.8, 0.1, 0.2],
    [0.3, 0.9, 0.7],
    [0.6, 0.2, 0.9],
    [0.4, 0.6, 0.1],
    [0.7, 0.4, 0.9],
    [0.9, 0.3, 0.5],
    [0.2, 0.7, 0.3],
    [0.5, 0.9, 0.6],
    [0.1, 0.3, 0.8],
    [0.8, 0.5, 0.2],
    [0.9, 0.1, 0.7],
    [0.3, 0.5, 0.9],
    [0.7, 0.8, 0.2],
    [0.2, 0.9, 0.4],
    [0.4, 0.2, 0.7],
    [0.6, 0.5, 0.3],
    [0.1, 0.4, 0.9],
    [0.7, 0.3, 0.6],
    [0.9, 0.2, 0.1],
    [0.5, 0.7, 0.4],
    [0.6, 0.8, 0.1],
    [0.3, 0.6, 0.5],
    [0.2, 0.1, 0.7],
    [0.4, 0.9, 0.2],
    [0.5, 0.3, 0.8],
    [0.1, 0.7, 0.5],
    [0.8, 0.6, 0.9],
    [0.3, 0.9, 0.1],
    [0.6, 0.7, 0.4]
    ]